server:
  port: 9991
spring:
  application:
    name: serverA
  profiles:
    active: yzh
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#  server:
#    enable-self-preservation: true
#    eviction-interval-timer-in-ms: 10000